apiVersion: v1
kind: Service
metadata:
  namespace: adduser
  name: adduser
  labels:
    app: adduser
spec:
  type: NodePort
  selector:
    app: adduser
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30000